function varargout = myGUI(varargin)
        
        
%   Get user screen size
        SC = get(0, 'ScreenSize');
        MaxMonitorX = SC(3);
        MaxMonitorY = SC(4);
       
%   Set the figure window size values
        NumberOfTabs = 4;
        MainFigScale = .8;          % Change this value to adjust the figure size
        MaxWindowX = round(MaxMonitorX*MainFigScale);
        MaxWindowY = round(MaxMonitorY*MainFigScale);
        %XBorder = (MaxMonitorX-MaxWindowX)/2;
        %YBorder = (MaxMonitorY-MaxWindowY)/2; 
        XBorder = (MaxWindowX)/20;
        YBorder = (MaxWindowY)/20; 
        TabOffset = 0;              % This value offsets the tabs inside the figure.
        ButtonHeight = 40;
        PanelWidth = MaxWindowX-2*TabOffset+4;
        PanelHeight = MaxWindowY-ButtonHeight-2*TabOffset;
        ButtonWidth = round((PanelWidth-NumberOfTabs)/NumberOfTabs);
        myButtonW = round(MaxWindowX/15);
        myButtonH = round(MaxWindowY/15);
        cameraX = 1392;
        cameraY = 1040; 
        
%   Set the color varables.  
        White = [1  1  1];            % White - Selected tab color     
        BGColor = .9*White;           % Light Grey - Background color

%   Set time for tooltip visibility  
        tm = javax.swing.ToolTipManager.sharedInstance; %static method to get ToolTipManager object
        %javaMethodEDT('setDismissDelay',tm, 500);
        initialDelay = javaMethodEDT('getInitialDelay',tm) %get the delay before display in milliseconds (=750 on my system)
        javaMethodEDT('setInitialDelay',tm,1000); %set tooltips to appear immediately
 
        dismissDelay = javaMethodEDT('getDismissDelay',tm) %get the delay before the tooltip disappears (=10000 (10 sec) on my system)
        javaMethodEDT('setDismissDelay',tm,1500); %set the dismiss delay to 2 seconds
        
%%   Create a container figure
        mainFig = figure(...
            'Units', 'pixels',...
            'Toolbar', 'none',...
            'Position',[ 2*XBorder, 2*YBorder, MaxWindowX, MaxWindowY ],...
            'NumberTitle', 'off',...
            'MenuBar', 'none',...
            'Resize', 'on',...
            'DockControls', 'off',...
            'Color', White);
        
        configurationData = struct('value1', -2, 'value2', -3, 'value3', 4);
        
%%  Create tab group
        mainTabGroup = uitabgroup(...
            'Parent', mainFig,...
            'Units', 'normalized',...
            'TabLocation','top');
           
%% Create individual tabs
        tab_1 = uitab('parent', mainTabGroup ,'title','Auto');
        tab_2 = uitab('parent', mainTabGroup ,'title','Manual');
        tab_3 = uitab('parent', mainTabGroup ,'title','Plots');
        tab_4 = uitab('parent', mainTabGroup ,'title','ActX');
    
%% Close button  (visible in all tabs)
        closeBtn= uicontrol(...
            'parent', mainFig,...
            'String','Close',...
            'Units', 'normalized',...
            'Position', [0.4 0.1 0.05 0.05], ...'Position', [MaxWindowX-1.5*myButtonW 0.5*myButtonH myButtonW myButtonH], 
            'Callback','close(gcbf)');
    
%% Test button  
        testBtn= uicontrol(...
            'parent', tab_1,...
            'String','Test',...
            'Units', 'normalized',...
            'Position', [0.1 0.1 0.05 0.05], ...
            'Callback','');
     
%% Preview area in tab 1
        placeholderImg = rand(cameraX, cameraY, 3);
        %camera_init
        %placeholderImg = prevImg;
        ImgOffset = 40;
        prevHaxes = axes(...
            'Parent', tab_1, ...
            'Box', 'off', ...
            'Units', 'normalized', ...
            'Position', [0.50 0.50 0.49 0.49]);
        %imagesc(randomImg,'Parent', prevHaxes);
        previewImage= imagesc(placeholderImg,'Parent', prevHaxes);
        %camera_init

%% ROOT TRACKING
        trackLocX= 0.5; 
        trackLocY= 0.15;
        trackLocW= 0.2;
        trackLocH= 0.2;
        XZhaxes = axes('Parent', tab_1, ...
            'Units', 'normalized', ...
            'Position', [trackLocX trackLocY trackLocW trackLocH]);
        plot(XZhaxes, 1:200, sin((1:200)./12));
        xlabel('X') ;
        ylabel('Z') ;
        
        YZhaxes = axes('Parent', tab_1, ...
            'Units', 'normalized', ...
            'Position', [trackLocX+trackLocW+0.088 trackLocY trackLocW trackLocH]);
        plot(YZhaxes, 1:200, tan((1:200)./12));
        xlabel('Y') ;
        ylabel('Z') ;
        
        
%%   Coordinate table in tab 1
    %   Build table for coordinates, to be used as an indicator
        %CoordData = cell(1,5); 
        CoordData = {-1 -1 -1 -1 3.1415};
        ColumnNames = {' X ' ' Y ' ' Z ' ' Cam X ' ' Focus '};
        Width = 60;
        ColumnWidths = {Width Width Width Width Width};
        RowNames = {'Position'};
        coordTabX = 0.01;
        coordTabY = 0.90;
        coordTabW = 0.4;
        coordTabH = 0.06;
        
    %   Build a table header
%         coordTable= uicontrol('Style', 'text',...
%             'Units', 'normalized',...
%             'Position', [coordTabX coordTabY coordTabW coordTabH],...
%             'Parent', tab_1, ...
%             'string', '  Tab 3 Table ',...
%             'BackgroundColor', White,...
%             'HorizontalAlignment', 'center',...
%             'FontName', 'arial',...
%             'FontWeight', 'bold',...
%             'FontSize', 12);

    %   Create the table
        coordTable= uitable(...
            'Units', 'normalized',...
            'Position',[coordTabX coordTabY coordTabW coordTabH],...
            'Parent', tab_1, ...
            'ColumnName', ColumnNames,...
            'ColumnWidth', ColumnWidths,...
            'RowName', RowNames,...
            'RearrangeableColumns' , 'off',...
            'Enable', 'off',...
            'Data', CoordData);
        
        ext = get(coordTable, 'Extent');
        set(coordTable, 'Position', [coordTabX coordTabY ext(3:4)]);

%%   TAB 1 controls

        configBtn= uicontrol(...
            'parent', tab_1,...
            'String','CONFIG',...
            'Units', 'normalized',...
            'Position', [0.04 0.775 0.05 0.05], ...
            'Callback',{@config_call, mainFig});
        
        startBtn= uicontrol(...
            'parent', tab_1,...
            'String','START',...
            'Units', 'normalized',...
            'Position', [0.1 0.775 0.05 0.05], ...
            'Callback','');
        
        pauseBtn= uicontrol(...
            'parent', tab_1,...
            'String','PAUSE',...
            'Units', 'normalized',...
            'Position', [0.16 0.775 0.05 0.05], ...
            'Callback','');
        
        stopBtn= uicontrol(...
            'parent', tab_1,...
            'String','STOP',...
            'Units', 'normalized',...
            'Position', [0.22 0.775 0.05 0.05], ...
            'Callback','');
        
end

%% Function that call the config GUI
function [] = config_call(varargin)
            % Callback for GUI_24 pushbutton.
            S = guidata(gcbf);  % Get the structure.
            set(0,'userdata',S);% Save it in the root.
            configGUI = make_subgui;
            % If user closes gui_passdata, close new one as well because it will 
            % error when  it tries to execute the callback otherwise.      
            set(S.mainFig,'deletefcn',{@fig_delet, configGUI});
end

%% On closing
function [] = fig_delet(varargin)
    % Executes when user closes gui_passdata.
        disp('OK OK OK');
        try
            delete(varargin{3})
        catch
            % Do nothing.
        end
end

function [configGUI] = make_subgui()
        configGUI = figure('units','pixels',...
            'menubar','none',...
            'position',[350 210 400 600]); % Create a new GUI.
        
        yBegin = uicontrol('style','edit',...
            'Units', 'normalized',...
            'position',[0.22 0.2 0.7 0.3],...
            'string','Type something, press return.',...
            'foregroundcolor','r');
            %'callback',{@E_call});

        discardConfBtn= uicontrol(...
            'String','DISC',...
            'Units', 'normalized',...
            'Position', [0.62 0.01 0.2 0.1], ...
            'Callback',@discardConfig);
        
        saveConfBtn= uicontrol(...
            'String','SAVE',...
            'Units', 'normalized',...
            'Position', [0.22 0.01 0.2 0.1], ...
            'Callback',@saveConfig);
          
        pause(1.25)
        S = get(0,'userdata');
        %str = get(S.ed,'string'); 
        set(yBegin,'string',str,'foregroundcolor','k')
        uicontrol(yBegin)
end

function [] = E_call(varargin)
    % Callback for secondary GUI editbox.
        S = get(0,'userdata');
        %set(S.ed,'string',get(gcbo,'string'))  % Set gui_passdata editbox string.
        close(gcbf)  % Close SubGUI.          
end

function saveConfig(source,callbackdata)
    % Save the parameters in the config panel
        disp('NOW SAVING');
end

function discardConfig(source,callbackdata)
    % Close config panel without saving
        disp('CONFIG DISCARDED');
        close(gcbf);
end