function TAB2_GUI(tab)
    buttonW = 0.05; %Width of standard buttons
    buttonH = 0.06; %Height of standard buttons
    smallW= 1.6*buttonW; % Width of small buttons
    smallH= 0.8*buttonH; % Height of small buttons
    line1= 0.05;
    line2= 0.05+ buttonH + 0.01;
    line1_2 = (line1 + line2)/2;
    line3= 0.05+ 2*(buttonH + 0.01);
    line4= 0.05+ 3*(buttonH + 0.01);
    line5= 0.05+ 4*(buttonH + 0.01);
    line6= 0.05+ 5*(buttonH + 0.01);
    line7= 0.05+ 6*(buttonH + 0.01);
    line8= 0.05+ 7*(buttonH + 0.01);
    line9= 0.05+ 8*(buttonH + 0.01)-0.04;
    line11= 0.05+ 10*(buttonH + 0.01)-0.08;
    line12= 0.05+ 11*(buttonH + 0.01)-0.08;
    line13= 0.05+ 12*(buttonH + 0.01)-0.04;
    line14= 0.05+ 13*(buttonH + 0.01)-0.04;
    
    column1 = 0.05;
    column2 = 0.05+2*buttonW+0.01;
    column1_2 = (column1 + column2) /2;
    column3 = 0.05+2*(2*buttonW+0.01);
    column4 = 0.05+3*(2*buttonW+0.01);
    column5 = 0.05+4*(2*buttonW+0.01);
    column6 = 0.05+5*(2*buttonW+0.01);
    %column7 = 0.05+6*(smallW+0.01);
    column7= column6 +(smallW+0.01); 
    column8 = column7 + (smallW+0.01);
    column9 = column8 + (smallW+0.01);
    %column8 = 0.05+7*(smallW+0.01);
    %column9 = 0.05+8*(smallW+0.01);
    
    uicontrol('Parent', tab, ... %%NORTH BUTTON (Sy)
        'Units', 'normalized', ...
        'Position', [column1_2 line3 2*buttonW buttonH], ...
        'String', '<HTML><center>&#9650<br/>Sy', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'Sy away from camera',...
        'Tag', 'Sy+', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
       
        %'FontName', 'arial',...
        %'FontWeight', 'bold',...

    uicontrol('Parent', tab, ... %%SOUTH BUTTON (Sy)
        'Units', 'normalized', ...
        'Position', [column1_2 line1 2*buttonW buttonH], ...
        'String', '<HTML><center>Sy<br/>&#9660', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'Sy toward from camera',...
        'Tag', 'Sy-', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
        %'Callback', {@moveStage, 2 , posStep }, ...

    uicontrol('Parent', tab, ... %%WEST BUTTON (Sx)
        'Units', 'normalized', ...
        'Position', [column1 line2 2*buttonW buttonH], ...
        'String', '<HTML>&#9668 Sx', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'Sx toward laser',...
        'Tag', 'Sx+', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
        %'Callback', {@moveStage, 1, negStep }, ...
      
    uicontrol('Parent', tab, ... %%EAST BUTTON (Sx)
        'Units', 'normalized', ...
        'Position', [column2 line2 2*buttonW buttonH], ...
        'String', '<HTML>Sx &#9658', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'Sx away from laser',...
        'Tag', 'Sx-', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
        %'Callback', {@moveStage, 1, posStep }, ...

    uicontrol('Parent', tab, ... %%UP BUTTON (Sz)
        'Units', 'normalized', ...
        'Position', [column4 line2 2*buttonW buttonH], ...
        'String', '<HTML><center>&#9651<br/>Sz UP', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'Sz up',...
        'Tag', 'Sz-', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
        %'Callback', {@moveStage, 3 , negStep }, ...
      
    uicontrol('Parent', tab, ... %%DOWN BUTTON (Sz)
        'Units', 'normalized', ...
        'Position', [column4 line1 2*buttonW buttonH], ...
        'String', '<HTML><center>Sz DW<br/>&#9661', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'Sz down',...
        'Tag', 'Sz+', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
        %'Callback', {@moveStage, 3, posStep }, ...
      
    uicontrol('Parent', tab, ...  %%F LEFT (F)
        'Units', 'normalized', ...
        'Position', [column4 line5 2*buttonW buttonH], ...
        'String', '<HTML><center>&#9650<br/>FOCUS', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'Focus toward sample',...
        'Tag', 'F+', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
        %'Callback', {@moveStage, 5, negStep }, ...
      
    uicontrol('Parent', tab, ... %%F RIGHT (F)
        'Units', 'normalized', ...
        'Position', [column4 line4 2*buttonW buttonH], ...
        'String', '<HTML><center>FOCUS<br/>&#9660', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'Focus away from sample',...
        'Tag', 'F-', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
        %'Callback', {@moveStage, 5, posStep } , ...
        
    uicontrol('Parent', tab, ...  %%C BACK (C)
        'Units', 'normalized', ...
        'Position', [column1 line5 2*buttonW buttonH], ...
        'String', '<HTML>&#9668 CAMx', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'C toward laser',...
        'Tag', 'C-', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
        %'Callback', {@moveStage, 4, negStep }, ...
        
    uicontrol('Parent', tab, ... %%C FWD (C)
        'Units', 'normalized', ...
        'Position', [column2 line5 2*buttonW buttonH], ...
        'String', '<HTML>CAMx &#9658', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Has to be inactive in order to tell left click from right click
        'HorizontalAlignment', 'center',...
        'tooltipString', 'C away from laser',...
        'Tag', 'C+', ...
        'ButtonDownFcn', {@GUI_clickMove }, ...%%%
        'FontSize', 10);
        %'Callback', {@moveStage, 4, posStep } , ...
    
    %INDICATE STEP SIZES IN uM (retrieve from myConfig.ini)
    confData= getappdata(gcf, 'confPar');
    smallStep= str2num(confData.application.smallstep)*1000;
    mediumStep= str2num(confData.application.mediumstep)*1000;
    largeStep= str2num(confData.application.largestep)*1000;
    initialExp= str2num(confData.camera.initiaexposure);
    if initialExp < 0.01
        initialExp= 0.01;
    end
    if initialExp > 1
        initialExp= 1;
    end
    clickLegend= sprintf('LEFT CLICK= %d um\nSHIFT+LEFT CLICK= %d um\nRIGHT CLICK= %d um', mediumStep, largeStep, smallStep); %DEFINE IN myConfig.ini
    
    uicontrol('Parent', tab, ...
        'Style','text',...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left',...
        'Position',[column6 line2 0.3 0.06],...
        'String', clickLegend);
        
    uicontrol('Parent', tab, ... %%Shutter OPEN
        'Units', 'normalized', ...
        'Position', [column1 line7 2*buttonW buttonH], ...
        'String', '<html>OPEN<br>Shutter', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'OPEN_SH',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
        %'Callback', {@toggleLaser, 1}, ...
        
    uicontrol('Parent', tab, ...  %%Shutter CLOSE
        'Units', 'normalized', ...
        'Position', [column2 line7 2*buttonW buttonH], ...
        'String', '<html>CLOSE<br>Shutter', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'CLOSE_SH',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
        %'Callback', {@toggleLaser, 0}, ...
      
    uicontrol('Parent', tab, ... %%LED ON
        'Units', 'normalized', ...
        'Position', [column1 line9 2*buttonW buttonH], ...
        'String', 'LED ON', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'LED_ON',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
        %'Callback', {@toggleLED, 1}, ...
        
    uicontrol('Parent', tab, ... %%LED OFF
        'Units', 'normalized', ...
        'Position', [column2 line9 2*buttonW buttonH], ...
        'String', 'LED OFF', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'LED_OFF',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
        %'Callback', {@toggleLED, 0}, ...
    
     uicontrol('Parent', tab, ... %%PUMP ON
        'Units', 'normalized', ...
        'Position', [column1 line11 2*buttonW buttonH], ...
        'String', 'PUMP ON', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'PUMP_ON',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
        
    uicontrol('Parent', tab, ... %%PUMP OFF
        'Units', 'normalized', ...
        'Position', [column2 line11 2*buttonW buttonH], ...
        'String', 'PUMP OFF', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'PUMP_OFF',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
    
    %Pump radio button: disabled when we decided to only use one
    %peristaltic pump.
    pumpRadio = uibuttongroup('Parent', tab, ...
        'Visible','off',...
        'Units' , 'normalized', ...   
        'Position',[column5-0.05 line11 2.5*buttonW 2.2*buttonH],...
        'SelectionChangedFcn','');
    
            pump1 = uicontrol( 'Parent', pumpRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.1 0.1 0.9 0.15],...
                  'String','PUMP FEED',...
                  'Tag', '1',...
                  'HandleVisibility','off');
              
            pump2 = uicontrol('Parent', pumpRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.1 0.425 0.9 0.15],...
                  'Enable', 'off',...
                  'String','PUMP 2',...
                  'Tag', '2', ...
                  'HandleVisibility','off');

            pump0 = uicontrol('Parent', pumpRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.1 0.75 0.9 0.15],...
                  'Enable', 'off',...
                  'String','BOTH',...
                  'Tag', '0', ...
                  'HandleVisibility','off');
              
          set(pumpRadio,'SelectedObject',pump1); % Initialize
          setappdata(gcf, 'pumpRadio', pumpRadio); % Add the container to the add data.
          
    pump1Speed= uicontrol('Parent', tab, ...
        'style','edit',...
        'Units', 'normalized',...
        'position',[column3 line11 0.12 0.05],...
        'string', '0.9' ,...
        'Callback', {@pumpEdit_call_calibrated, 1},...
        'FontSize', 10, ...
        'foregroundcolor','default');
    setappdata(gcf, 'pump1Speed', pump1Speed);

    pump1Label= uicontrol('Parent', tab, ...
        'Style','text',...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left',...
        'Position',[column3 line11+0.052 0.15 0.02],...
        'String','PUMP FEED (mL/min)');
    
    % CODE FOR SECOND PUMP SPEED, NOW DISABLED
    pump2Speed= uicontrol('Parent', tab, ...
        'style','edit',...
        'Units', 'normalized',...
        'position',[column5+0.02 line11 0.12 0.05],...
        'Enable', 'Inactive',...
        'Visible','off',...
        'string', '0.9' ,...
        'Callback', {@pumpEdit_call_calibrated, 2},...
        'FontSize', 10, ...
        'foregroundcolor','default');
    setappdata(gcf, 'pump2Speed', pump2Speed);

    pump2Label= uicontrol('Parent', tab, ...
        'Style','text',...
        'Visible','off',...
        'Units', 'normalized',...
        'Position',[column5+0.02 line11+0.052 0.12 0.02],...
        'String','PUMP 2 (mL/min)');
    
     uicontrol('Parent', tab, ... %%PREVIEW ON
        'Units', 'normalized', ...
        'Position', [column1 line13 2*buttonW buttonH], ...
        'String', 'PREV ON', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'PREV_ON',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
        
    uicontrol('Parent', tab, ... %%PREVIEW OFF
        'Units', 'normalized', ...
        'Position', [column2 line13 2*buttonW buttonH], ...
        'String', 'PREV OFF', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'PREV_OFF',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
    
    % CAMERA EXPOSURE
    brightSld = uicontrol('Parent', tab,...
        'Style', 'slider',...
        'Min', 0.0100,... %Min 1.4e-05  
        'Max', 1,... %Max 1.0e+03
        'Value', initialExp,...
        'Units', 'normalized',...
        'Position', [column4 line13  0.2 0.02],...
        'Tag', 'exposure',...
        'Callback', {@GUI_camera_set});
    setappdata(gcf, 'brightSld', brightSld);
    
    brightLabel= uicontrol('Parent', tab, ...
        'Style','text',...
        'Units', 'normalized',...
        'Position',[column4 line13+0.025 0.2 0.02],...
        'String',['EXPOSURE ' num2str(initialExp*1000, '%3.2f') ' (ms)']);
    setappdata(gcf, 'brightLabel', brightLabel);
    
    gainSld = uicontrol('Parent', tab,...
        'Style', 'slider',...
        'Min', 0.8,...
        'Max', 15,...
        'Value', 1,...
        'Units', 'normalized',...
        'Position', [column4 line14  0.2 0.02],...
        'Tag', 'gain',...
        'Callback', {@GUI_camera_set}); 
    
     gainLabel= uicontrol('Parent', tab, ...
        'Style','text',...
        'Units', 'normalized',...
        'Position',[column4 line14+0.025 0.2 0.02],...
        'String',['GAIN ' num2str(1, '%2.1f' )]);
    setappdata(gcf, 'gainLabel', gainLabel);
    
  % ====HOME BUTTON====
    uicontrol('Parent', tab, ... %%HOME
        'Units', 'normalized', ...
        'Position', [column6 line5 smallW smallH], ...
        'String', '<HTML><FONT size="-1">HOME', ...
        'Style', 'pushbutton',...
        'Enable', 'on',... 
        'HorizontalAlignment', 'center',...
        'Tag', 'HOME',...
        'Callback', {@GUI_clickOther}, ...%%%
        'FontSize', 10);  
  
  % ====AF BUTTON====
    uicontrol('Parent', tab, ... %%AUTOFOCUS
        'Units', 'normalized', ...
        'Position', [column7 line5 smallW smallH], ...
        'String', '<HTML><FONT size="-1">AUTO<br>FOCUS', ...
        'Style', 'pushbutton',...
        'Enable', 'on',... 
        'HorizontalAlignment', 'center',...
        'Tag', 'A_FOCUS',...
        'Callback', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
%{    
    % ====SAVE COORDINATE==== button
    uicontrol('Parent', tab, ... 
        'Units', 'normalized', ...
        'Position', [column8 line5 smallW smallH], ...
        'String', '<HTML><FONT size="-1">SAVE<br>COORD', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'SAVE_COORD',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
    
  % ====LOAD COORDINATE==== button
    uicontrol('Parent', tab, ... 
        'Units', 'normalized', ...
        'Position', [column9 line5 smallW smallH], ...
        'String', '<HTML><FONT size="-1">LOAD<br>COORD', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',... %% Not really needed for these buttons, but maintains consinstent behaviour
        'HorizontalAlignment', 'center',...
        'Tag', 'LOAD_COORD',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10); 
%}
        
  % ====FOCUS BUTTON====
   uicontrol('Parent', tab, ... %%FOCUS
        'Units', 'normalized', ...
        'Position', [column8 line4-0.06 2*buttonW buttonH], ...
        'String', 'FOCUS', ...
        'Style', 'pushbutton',...
        'Enable', 'off',... 
        'Visible','off',...
        'HorizontalAlignment', 'center',...
        'Tag', 'FOCUS',...
        'Callback', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
    

    
    
    % TEMPORARY BUTTON
        uicontrol('Parent', tab, ... %%JUNK
        'Units', 'normalized', ...
        'Position', [column7 line6 smallW smallH], ...
        'String', '<HTML><FONT size="-1">TMP', ...
        'Style', 'pushbutton',...
        'Enable', 'off',... 
        'HorizontalAlignment', 'center',...
        'Tag', 'TMP',...
        'Callback', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
    
   % ====LOCK AXIS====
    lockYCheck = uicontrol('Parent', tab, ...
            'Style','checkbox',...
            'String','LOCK Sy-F',...
            'Value',0,...
            'Units', 'normalized', ...
            'Position',[column6 line1+0.025 0.11 0.023]);
    setappdata(gcf, 'lockYCheck', lockYCheck);
    
    lockXCheck = uicontrol('Parent', tab, ...
            'Style','checkbox',...
            'String','LOCK Sx-Cx',...
            'Value',0,...
            'Units', 'normalized', ...
            'Position',[column6 line1 0.11 0.023]);
    setappdata(gcf, 'lockXCheck', lockXCheck);
 
    % ====FILTER WHEEL====
     fw_label1= upper(confData.filterwh.label1);
     fw_label2= upper(confData.filterwh.label2);
     fw_label3= upper(confData.filterwh.label3);
     fw_label4= upper(confData.filterwh.label4);
     fw_label5= upper(confData.filterwh.label5);
     fw_label6= upper(confData.filterwh.label6);
     FWRadio = uibuttongroup('Parent', tab, ...
        'Visible','on',...
        'Units' , 'normalized', ...   
        'Position',[column7 line7 4*buttonW 2.2*buttonH],...
        'SelectionChangedFcn','');
    
            
            pos1 = uicontrol( 'Parent', FWRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.1 0.75 0.9 0.15],...
                  'String',fw_label1,...
                  'Tag', '1',...
                  'Callback', {@GUI_FWRadio, 1},...
                  'HandleVisibility','off');
              
            pos2 = uicontrol('Parent', FWRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.1 0.425 0.9 0.15],...
                  'String',fw_label2,...
                  'Tag', '2', ...
                  'Callback', {@GUI_FWRadio, 2},...
                  'HandleVisibility','off');

            pos3 = uicontrol('Parent', FWRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.1 0.1 0.9 0.15],...
                  'String', fw_label3,...
                  'Tag', '3', ...
                  'Callback', {@GUI_FWRadio, 3},...
                  'HandleVisibility','off');
              
          pos4 = uicontrol('Parent', FWRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.6 0.75 0.9 0.15],...
                  'String', fw_label4,...
                  'Tag', '4', ...
                  'Callback', {@GUI_FWRadio, 4},...
                  'HandleVisibility','off');
              
          pos5 = uicontrol('Parent', FWRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.6 0.425 0.9 0.15],...
                  'String', fw_label5,...
                  'Tag', '5', ...
                  'Callback', {@GUI_FWRadio, 5},...
                  'HandleVisibility','off');
              
           pos6 = uicontrol('Parent', FWRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.6 0.1 0.9 0.15],...
                  'String', fw_label6,...
                  'Tag', '6', ...
                  'Callback', {@GUI_FWRadio, 6},...
                  'HandleVisibility','off');
              
          set(FWRadio,'SelectedObject', pos1); % Initialize to POS 1.
          setappdata(gcf, 'FWRadio', FWRadio); % Add the container to the add data.
          
     FWLabel= uicontrol('Parent', tab, ...
        'Style','text',...
        'Units', 'normalized',...
        'Position',[column7 line7+2*buttonH+0.015 0.2 0.02],...
        'HorizontalAlignment', 'left',...
        'String',['FILTER WHEEL']);
    
    
    % ====PELTIER====
     PeltRadio = uibuttongroup('Parent', tab, ...
        'Visible','on',...
        'Units' , 'normalized', ...   
        'Position',[column7 line11 4*buttonW 2.2*buttonH],...
        'SelectionChangedFcn','');
    
            peltpos1 = uicontrol( 'Parent', PeltRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.1 0.75 0.9 0.15],...
                  'String','OFF',...
                  'Tag', '1',...
                  'Callback', {@GUI_peltierRadio, 1},...
                  'HandleVisibility','off');
              
            peltpos2 = uicontrol('Parent', PeltRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.1 0.425 0.9 0.15],...
                  'String','ON',...
                  'Tag', '2', ...
                  'Callback', {@GUI_peltierRadio, 2},...
                  'HandleVisibility','off');

            peltpos3 = uicontrol('Parent', PeltRadio,...
                  'Style', 'radiobutton',...
                  'Units' , 'normalized', ...
                  'Position', [0.1 0.1 0.9 0.15],...
                  'String','AUTO',...
                  'Tag', '3', ...
                  'Callback', {@GUI_peltierRadio, 3},...
                  'HandleVisibility','off');
              
            targetTemp= uicontrol('Style','edit',...
                'Units', 'normalized',...
                'Parent', PeltRadio,...
                'Position',[0.5 0.058 0.23 0.20],...
                'BackGroundColor', 'white',...
                'Callback', {@GUI_peltierTargetEdit},...
                'Enable', 'off',...
                'HorizontalAlignment', 'left',...
                'String','----');
            
            targetTempLabel= uicontrol('Parent', PeltRadio, ...
                 'Style','text',...
                 'Units', 'normalized',...
                 'Position',[0.76 0.058 0.12 0.2],...
                 'HorizontalAlignment', 'left',...
                 'String','(C)');
              
          set(PeltRadio,'SelectedObject', peltpos1); % Initialize to POS 1.
          setappdata(gcf, 'PeltRadio', PeltRadio); % Add the container to the add data.
          setappdata(gcf, 'targetTemp', targetTemp); % Add the container to the add data.
          
      PeltLabel= uicontrol('Parent', tab, ...
        'Style','text',...
        'Units', 'normalized',...
        'Position',[ column7 line11+2*buttonH+0.015 0.2 0.02],...
        'HorizontalAlignment', 'left',...
        'String', 'PELTIER');
