function TAB5_GUI(tab)
%%  Define content of tab #5
%   Contains controls for scan routines
%   The tab is divided in a grid so that it is easier to align objects.
    buttonW = 0.05; %Width of standard buttons
    buttonH = 0.06; %Height of standard buttons
    smallW= 1.6*buttonW; % Width of small buttons
    smallH= 0.8*buttonH; % Height of small buttons

    line1= 0.05;
    line2= 0.05+ buttonH + 0.01;
    line1_2 = (line1 + line2)/2;
    line3= 0.05+ 2*(buttonH + 0.01);
    line4= 0.05+ 3*(buttonH + 0.01);
    line5= 0.05+ 4*(buttonH + 0.01)-0.04;
    line7= 0.05+ 6*(buttonH + 0.01)-0.04;
    line8= 0.05+ 7*(buttonH + 0.01)-0.04;
    line9= 0.05+ 8*(buttonH + 0.01)-0.04;
    line10= 0.05+ 9*(buttonH + 0.01)-0.04;
    line11= 0.05+ 10*(buttonH + 0.01)-0.08;
    line13= 0.05+ 12*(buttonH + 0.01)-0.04;
    line14= 0.05+ 13*(buttonH + 0.01)-0.04;
    line15= 0.05+ 14*(buttonH + 0.01)-0.04;
    
    column1 = 0.05;
    column2 = 0.05+2*buttonW+0.01;
    column1_2 = (column1 + column2) /2;
    column3 = 0.05+2*(2*buttonW+0.01);
    column4 = 0.05+3*(2*buttonW+0.01);
    column5 = 0.05+4*(2*buttonW+0.01);
    
    column6 = 0.05+5*(2*buttonW+0.01);
    column7= column6 +(smallW+0.01); 
    column8 = column7 + (smallW+0.01);
    column9 = column8 + (smallW+0.01);
    
%   SAVE slices button
    uicontrol('Parent', tab, ... 
        'Units', 'normalized', ...
        'Position', [column2 line7 2*buttonW buttonH], ...
        'String', 'SLICE', ...
        'Style', 'pushbutton',...
        'Enable', 'on',...
        'HorizontalAlignment', 'center',...
        'Tag', 'SLICE',...
        'Callback', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
    
    uicontrol('Parent', tab, ... 
        'Units', 'normalized', ...
        'Position', [column1 line7 2*buttonW buttonH], ...
        'String', 'SNAP', ...
        'Style', 'pushbutton',...
        'Enable', 'Inactive',...
        'HorizontalAlignment', 'center',...
        'Tag', 'SNAP',...
        'ButtonDownFcn', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
    
%   FILENAME edit
    fNameField =uicontrol('Parent', tab, ... 
        'Units', 'normalized', ...
        'Position', [column1 line8 4*buttonW 0.5*buttonH], ...
        'Style', 'edit',...
        'HorizontalAlignment', 'left',...
        'String', 'myDefault.tif',...
        'FontSize', 10);
    setappdata(gcf, 'fNameField', fNameField);
    
    uicontrol('Style','text',...
        'Units', 'normalized',...
        'Parent', tab,...
        'Position',[column1 line8+0.6*buttonH 4*buttonW 0.02],...
        'HorizontalAlignment', 'left',...
        'String','File name:');
   
%   SCAN TPS BUTTON
    uicontrol('Parent', tab, ... 
        'Units', 'normalized', ...
        'Position', [column3 line7 2*buttonW buttonH], ...
        'String', '<HTML>SCAN<br>TPS', ...
        'Style', 'pushbutton',...
        'Enable', 'on',...
        'HorizontalAlignment', 'center',...
        'Tag', 'SCAN_TPS',...
        'Callback', {@GUI_scanTPS}, ...%%%
        'FontSize', 10);
    
%   SCAN PSF
    uicontrol('Parent', tab, ... 
        'Units', 'normalized', ...
        'Position', [column4 line7 2*buttonW buttonH], ...
        'String', '<HTML>SCAN<br>PSF', ...
        'Style', 'pushbutton',...
        'Enable', 'on',...
        'HorizontalAlignment', 'center',...
        'Tag', 'SCAN_PSF',...
        'Callback', {@GUI_scanPSF}, ...%%%
        'FontSize', 10);
    
%   ROOT SEARCH BUTTON
    uicontrol('Parent', tab, ... %%ROOT
        'Units', 'normalized', ...
        'Position', [column1 line4 2*buttonW buttonH], ...
        'String', '<HTML><FONT size="-1">ROOT<br>SEARCH', ...
        'FontUnits', 'points',...
        'Style', 'pushbutton',...
        'Enable', 'on',... 
        'HorizontalAlignment', 'center',...
        'Tag', 'ROOT_SRC',...
        'Callback', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
  
%   LOCAL SEARCH BUTTON
    uicontrol('Parent', tab, ... %%LOCAL
        'Units', 'normalized', ...
        'Position', [column2 line4 2*buttonW buttonH], ...
        'String', '<HTML><FONT size="-1">LOCAL<br>SEARCH', ...
        'FontUnits', 'points',...
        'Style', 'pushbutton',...
        'Enable', 'on',... 
        'HorizontalAlignment', 'center',...
        'Tag', 'LOCAL_SRC',...
        'Callback', {@GUI_clickOther} );
    
%   BACKGROUND SNAP
    uicontrol('Parent', tab, ... %%BG SNAP
        'Units', 'normalized', ...
        'Position', [column2 line3 2*buttonW buttonH], ...
        'String', '<HTML><FONT size="-1">BGRD<br>SNAP', ...
        'FontUnits', 'points',...
        'Style', 'pushbutton',...
        'Enable', 'on',... 
        'HorizontalAlignment', 'center',...
        'Tag', 'BACKGROUND_SNAP',...
        'Callback', {@GUI_clickOther} );
   
%   CHECK BOX FOR SLOW SEARCH
    slowSrchCheck = uicontrol('Parent', tab, ...
            'Style','checkbox',...
            'String','SLOW',...
            'Value',0,...
            'Units', 'normalized', ...
            'Position',[column3 line4+0.025 0.11 0.023]);
    setappdata(gcf, 'slowSrchCheck', slowSrchCheck);
    
%   ABORT SEARCH BUTTON
    abort_src_btn= uicontrol('Parent', tab, ... %%ABORT_SRC
        'Units', 'normalized', ...
        'Position', [column4 line4 2*buttonW buttonH], ...
        'String', '<HTML><FONT size="-1">ABORT<br>SEARCH', ...
        'FontUnits', 'points',...
        'Style', 'pushbutton',...
        'Enable', 'off',... 
        'HorizontalAlignment', 'center',...
        'Tag', 'ABORT_SRC',...
        'Callback', {@GUI_clickOther} );  
    setappdata(gcf, 'abort_src_btn', abort_src_btn);
    
%   SETUP
   uicontrol('Parent', tab, ... %%SETUP (sets the motors to locate cuvette corner in TPS and focus)
        'Units', 'normalized', ...
        'Position', [column1 line3 2*buttonW buttonH], ...
        'String', '<HTML><FONT size="-1">SETUP<br>CUVETTE', ...
        'Style', 'pushbutton',...
        'Enable', 'on',... 
        'Visible','on',...
        'HorizontalAlignment', 'center',...
        'Tag', 'SETUP',...
        'Callback', {@GUI_clickOther}, ...%%%
        'FontSize', 10);
    
end