function [fitresult, gof] = createFit(x, y, z)
%CREATEFIT(X,Y,Z)
%  Create a fit.
%
%  Data for 'Gauss2d' fit:
%      X Input : x
%      Y Input : y
%      Z Output: z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Jul-2015 15:43:48


%% Fit: 'Gauss2d'.
[xData, yData, zData] = prepareSurfaceData( x, y, z );

% Set up fittype and options.
ft = fittype( 'ped+a1*exp(-(x-x0)^2/(2*sigmax^2)-(y-y0)^2/(2*sigmay^2))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 -Inf -Inf -Inf -Inf];
opts.StartPoint = [15 0 1 1 15 15];
opts.Upper = [Inf 15 Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );


% Plot fit with data.
% figure( 'Name', 'Gauss2d' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'Gauss2d', 'z vs. x, y', 'Location', 'NorthEast' );
% % Label axes
% xlabel x
% ylabel y
% zlabel z
% grid on
% view( -17.5, 8.0 );


