function web_test_figure( ~ )

mainFig = figure(...
            'Units', 'pixels',...
            'Toolbar', 'none',...
            'Position',[ 100, 100, 800, 600 ],...
            'NumberTitle', 'off',...
            'Name', 'Main GUI',...
            'MenuBar', 'none',...
            'Resize', 'on',...
            'DockControls', 'off');
        
        
 prevHaxes = axes(...
        'Parent', mainFig, ...
        'Box', 'off', ...
        'Units', 'normalized', ...
        'Position', [0.24 0.35 0.45 0.5]);

    blankimage = ones(200,200,3);
    previewImage= imagesc(blankimage,'Parent', prevHaxes);

    cam = webcam(1);
    preview(cam, previewImage);
    pause(3);
    
    closePreview(cam); % <-- THIS IS WHERE THINGS GO HORRIBLY
    web_close(cam);

end

